export const REQUEST_URL_TO_BE_SHORTENED = "REQUEST_URL_TO_BE_SHORTENED";
export const RESPONSE_URL_TO_BE_SHORTENED_SUCCESS = "RESPONSE_URL_TO_BE_SHORTENED_SUCCESS";
export const RESPONSE_URL_TO_BE_SHORTENED_ERROR = "RESPONSE_URL_TO_BE_SHORTENED_ERROR";